### ISSUE TITLE
can you show an example of a model base file

### ISSUE THREAD

**Issue by leore** [lob/hapi-bookshelf-models#2]

**Comment by robertd** [comment]
+1

**Comment by robertd** [comment]
I copied this from [here](https://github.com/lob/hapi-bookshelf-models/blob/master/test/index.test.js#L65) and it works....
```
base: function (bookshelf) {
            return bookshelf.Model.extend({});
          }
```

**Comment by pon** [comment]
Yup that works and doesn't make any modification to the base model. I'll add an example today that extends it. Also probably add an update to make the base optional.

For example if you wanted to make sure all models had timestamps you could do 

```
function (bookshelf) {
  return bookshelf.Model.extend({
    hasTimestamps: true
  });
}
```
