### ISSUE TITLE
Cannot find module 'pg.js'

### ISSUE THREAD

**Issue by ericsvendsen** [lob/hapi-bookshelf-models#23]
Following your directions for registering the plugin produces the error
`Bad Knex Options: Error: Cannot find module 'pg.js'`

If I run `npm install pg`, then I receive this error:
`TypeError: require(...) is not a function` at `at Object.exports.register (/node_modules/hapi-bookshelf-models/lib/index.js:69:11)`.

What am I missing?

**Comment by robinjoseph08** [comment]
Hmm, that's a bit odd. `require` should be available in all node environments.

What version of node are you running?

**Comment by ericsvendsen** [comment]
I think I found the problem. There seems to be a comma missing in the argument list beginning on line 67 of lib/index.js. Here is what is in the package by default:

```javascript
bookshelf.model(modelName,
          require(path.resolve(path.join(modelDir, fileName)))
          (baseModel, bookshelf));
```

Adding a comma after the `require` resolves the issue for me:

```javascript
bookshelf.model(modelName,
          require(path.resolve(path.join(modelDir, fileName))),
          (baseModel, bookshelf));
```
If this is indeed the proper solution, it seems like more people than me would be having issues. That's why I'm not convinced this is it - other than the fact that I can now run my project. Regardless I submitted a PR for this in case it can resolve the issue. Thanks!

Oh, and I'm running Node 5.4.1 by the way.

**Comment by robinjoseph08** [comment]
Hmm, you're right in saying more people would have this issue if that comma was necessary. The extra comma also makes the Travis build fail. But I'm really curious as to why it got your setup working.

Is it possible your local copy of `hapi-bookshelf-models` (that resides in your projects `node_modules`) was altered somehow? If you're saving your dependencies into your `package.json`, can you try deleting your `node_modules` directory and running a clean `npm install`? Does the issue still persist?

**Comment by charlesbjohnson** [comment]
Hi @ericsvendsen, can you post a snippet of what one of your bookshelf models looks like? It seems that one could encounter this issue if one of his/her models (as picked up by the `models` directory option during plugin registration) was not exported wholly as a function.

In other words, this would not work:

```js
exports = function (baseModel, bookshelf) {
  return bookshelf.Model.extend({ tableName: 'foobar' });
};
```  

While this is fine:

```js
module.exports = function (baseModel, bookshelf) {
  return bookshelf.Model.extend({ tableName: 'foobar' });
};
```

[Related docs](https://github.com/lob/hapi-bookshelf-models#defining-models).

**Comment by ericsvendsen** [comment]
@robinjoseph08 I did try deleting and reinstalling my dependencies, and received the same results.

@charlesbjohnson my bookshelf model looked exactly like the `role.js` example from the "Defining Models" section of the readme.

I wish I could help you guys troubleshoot this some more, but I went in so many different directions when trying to work through this that I don't think I can get back to where I was (I'm now just using bookshelf directly). I'm 99.9% sure it was something I had screwed up somewhere, and I don't want you to spend any more of your time troubleshooting what is most certainly my fault to begin with.

Therefore I'm closing the issue and the PR. It's up to you if you want to reopen it, and if I have some spare time this week I can try and remember where things were when this was happening. Otherwise, I was never here....

**Comment by robinjoseph08** [comment]
@ericsvendsen I'm glad you still able to use Bookshelf directly to get it working, though I'm sorry you weren't able to use this module. If you try using it again and run into any more issues, definitely let us know and we'll see if we can figure it out :+1:
