### ISSUE TITLE
Execute a query on the model within instance method

### ISSUE THREAD

**Issue by ghost** [lob/hapi-bookshelf-models#31]
Is there a way to execute a query on the model within an instance method of the model?

**Comment by robinjoseph08** [comment]
Hi @vasanthpandia,

This module doesn't actually do anything special to the Bookshelf models. It just exposes them in a different way. So it seems your question is more a Bookshelf question than a hapi-bookshelf-models question.

Either way, I'm not entire sure if I understand your question. Once you have the model instance, you can do anything with it, such as [fetching](http://bookshelfjs.org/#Model-instance-fetch) from the DB and [saving](http://bookshelfjs.org/#Model-instance-save) a new (or updated) row. If that doesn't answer your question, can you give me an example of what you're trying to do, and I'll try to point you in the right direction?
